'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8009
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DataPall"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DataPall
    Inherits Global.System.Data.DataSet
    
    Private tableLABEL As LABELDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("LABEL")) Is Nothing) Then
                MyBase.Tables.Add(New LABELDataTable(ds.Tables("LABEL")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property LABEL() As LABELDataTable
        Get
            Return Me.tableLABEL
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DataPall = CType(MyBase.Clone,DataPall)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("LABEL")) Is Nothing) Then
                MyBase.Tables.Add(New LABELDataTable(ds.Tables("LABEL")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableLABEL = CType(MyBase.Tables("LABEL"),LABELDataTable)
        If (initTable = true) Then
            If (Not (Me.tableLABEL) Is Nothing) Then
                Me.tableLABEL.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "DataPall"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DataSet3.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableLABEL = New LABELDataTable
        MyBase.Tables.Add(Me.tableLABEL)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeLABEL() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DataPall = New DataPall
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub LABELRowChangeEventHandler(ByVal sender As Object, ByVal e As LABELRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class LABELDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnPPREFX As Global.System.Data.DataColumn
        
        Private columnPSEQNO As Global.System.Data.DataColumn
        
        Private columnPDELNO As Global.System.Data.DataColumn
        
        Private columnPCUST As Global.System.Data.DataColumn
        
        Private columnPMAKER As Global.System.Data.DataColumn
        
        Private columnPPART As Global.System.Data.DataColumn
        
        Private columnPPDCHG As Global.System.Data.DataColumn
        
        Private columnPSENO As Global.System.Data.DataColumn
        
        Private columnPBQTY As Global.System.Data.DataColumn
        
        Private columnPEMTRY As Global.System.Data.DataColumn
        
        Private columnPQRDAT As Global.System.Data.DataColumn
        
        Private columnPITEM As Global.System.Data.DataColumn
        
        Private columnPDELDT As Global.System.Data.DataColumn
        
        Private columnPMODEL As Global.System.Data.DataColumn
        
        Private columnPDESC1 As Global.System.Data.DataColumn
        
        Private columnPSTAT As Global.System.Data.DataColumn
        
        Private columnPCRDT As Global.System.Data.DataColumn
        
        Private columnPCTMT As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "LABEL"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PPREFXColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPPREFX
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PSEQNOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPSEQNO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PDELNOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPDELNO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PCUSTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPCUST
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PMAKERColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPMAKER
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PPARTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPPART
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PPDCHGColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPPDCHG
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PSENOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPSENO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PBQTYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPBQTY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PEMTRYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPEMTRY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PQRDATColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPQRDAT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PITEMColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPITEM
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PDELDTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPDELDT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PMODELColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPMODEL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PDESC1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnPDESC1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PSTATColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPSTAT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PCRDTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPCRDT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PCTMTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPCTMT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As LABELRow
            Get
                Return CType(Me.Rows(index),LABELRow)
            End Get
        End Property
        
        Public Event LABELRowChanging As LABELRowChangeEventHandler
        
        Public Event LABELRowChanged As LABELRowChangeEventHandler
        
        Public Event LABELRowDeleting As LABELRowChangeEventHandler
        
        Public Event LABELRowDeleted As LABELRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddLABELRow(ByVal row As LABELRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddLABELRow( _
                    ByVal PPREFX As String,  _
                    ByVal PSEQNO As Decimal,  _
                    ByVal PDELNO As String,  _
                    ByVal PCUST As String,  _
                    ByVal PMAKER As String,  _
                    ByVal PPART As String,  _
                    ByVal PPDCHG As String,  _
                    ByVal PSENO As String,  _
                    ByVal PBQTY As Decimal,  _
                    ByVal PEMTRY As Decimal,  _
                    ByVal PQRDAT As String,  _
                    ByVal PITEM As Decimal,  _
                    ByVal PDELDT As Decimal,  _
                    ByVal PMODEL As String,  _
                    ByVal PDESC1 As String,  _
                    ByVal PSTAT As String,  _
                    ByVal PCRDT As Decimal,  _
                    ByVal PCTMT As Decimal) As LABELRow
            Dim rowLABELRow As LABELRow = CType(Me.NewRow,LABELRow)
            Dim columnValuesArray() As Object = New Object() {PPREFX, PSEQNO, PDELNO, PCUST, PMAKER, PPART, PPDCHG, PSENO, PBQTY, PEMTRY, PQRDAT, PITEM, PDELDT, PMODEL, PDESC1, PSTAT, PCRDT, PCTMT}
            rowLABELRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowLABELRow)
            Return rowLABELRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function FindByPQRDATPSTAT(ByVal PQRDAT As String, ByVal PSTAT As String) As LABELRow
            Return CType(Me.Rows.Find(New Object() {PQRDAT, PSTAT}),LABELRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As LABELDataTable = CType(MyBase.Clone,LABELDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New LABELDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnPPREFX = MyBase.Columns("PPREFX")
            Me.columnPSEQNO = MyBase.Columns("PSEQNO")
            Me.columnPDELNO = MyBase.Columns("PDELNO")
            Me.columnPCUST = MyBase.Columns("PCUST")
            Me.columnPMAKER = MyBase.Columns("PMAKER")
            Me.columnPPART = MyBase.Columns("PPART")
            Me.columnPPDCHG = MyBase.Columns("PPDCHG")
            Me.columnPSENO = MyBase.Columns("PSENO")
            Me.columnPBQTY = MyBase.Columns("PBQTY")
            Me.columnPEMTRY = MyBase.Columns("PEMTRY")
            Me.columnPQRDAT = MyBase.Columns("PQRDAT")
            Me.columnPITEM = MyBase.Columns("PITEM")
            Me.columnPDELDT = MyBase.Columns("PDELDT")
            Me.columnPMODEL = MyBase.Columns("PMODEL")
            Me.columnPDESC1 = MyBase.Columns("PDESC1")
            Me.columnPSTAT = MyBase.Columns("PSTAT")
            Me.columnPCRDT = MyBase.Columns("PCRDT")
            Me.columnPCTMT = MyBase.Columns("PCTMT")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnPPREFX = New Global.System.Data.DataColumn("PPREFX", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPPREFX)
            Me.columnPSEQNO = New Global.System.Data.DataColumn("PSEQNO", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPSEQNO)
            Me.columnPDELNO = New Global.System.Data.DataColumn("PDELNO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPDELNO)
            Me.columnPCUST = New Global.System.Data.DataColumn("PCUST", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPCUST)
            Me.columnPMAKER = New Global.System.Data.DataColumn("PMAKER", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPMAKER)
            Me.columnPPART = New Global.System.Data.DataColumn("PPART", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPPART)
            Me.columnPPDCHG = New Global.System.Data.DataColumn("PPDCHG", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPPDCHG)
            Me.columnPSENO = New Global.System.Data.DataColumn("PSENO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPSENO)
            Me.columnPBQTY = New Global.System.Data.DataColumn("PBQTY", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPBQTY)
            Me.columnPEMTRY = New Global.System.Data.DataColumn("PEMTRY", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPEMTRY)
            Me.columnPQRDAT = New Global.System.Data.DataColumn("PQRDAT", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPQRDAT)
            Me.columnPITEM = New Global.System.Data.DataColumn("PITEM", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPITEM)
            Me.columnPDELDT = New Global.System.Data.DataColumn("PDELDT", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPDELDT)
            Me.columnPMODEL = New Global.System.Data.DataColumn("PMODEL", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPMODEL)
            Me.columnPDESC1 = New Global.System.Data.DataColumn("PDESC1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPDESC1)
            Me.columnPSTAT = New Global.System.Data.DataColumn("PSTAT", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPSTAT)
            Me.columnPCRDT = New Global.System.Data.DataColumn("PCRDT", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPCRDT)
            Me.columnPCTMT = New Global.System.Data.DataColumn("PCTMT", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPCTMT)
            Me.Constraints.Add(New Global.System.Data.UniqueConstraint("Constraint1", New Global.System.Data.DataColumn() {Me.columnPQRDAT, Me.columnPSTAT}, true))
            Me.columnPPREFX.MaxLength = 5
            Me.columnPDELNO.MaxLength = 8
            Me.columnPCUST.MaxLength = 50
            Me.columnPMAKER.MaxLength = 15
            Me.columnPPART.AllowDBNull = false
            Me.columnPPART.MaxLength = 25
            Me.columnPPDCHG.AllowDBNull = false
            Me.columnPPDCHG.MaxLength = 5
            Me.columnPSENO.MaxLength = 50
            Me.columnPQRDAT.AllowDBNull = false
            Me.columnPQRDAT.MaxLength = 120
            Me.columnPMODEL.MaxLength = 50
            Me.columnPDESC1.MaxLength = 20
            Me.columnPSTAT.AllowDBNull = false
            Me.columnPSTAT.MaxLength = 1
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewLABELRow() As LABELRow
            Return CType(Me.NewRow,LABELRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New LABELRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(LABELRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.LABELRowChangedEvent) Is Nothing) Then
                RaiseEvent LABELRowChanged(Me, New LABELRowChangeEvent(CType(e.Row,LABELRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.LABELRowChangingEvent) Is Nothing) Then
                RaiseEvent LABELRowChanging(Me, New LABELRowChangeEvent(CType(e.Row,LABELRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.LABELRowDeletedEvent) Is Nothing) Then
                RaiseEvent LABELRowDeleted(Me, New LABELRowChangeEvent(CType(e.Row,LABELRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.LABELRowDeletingEvent) Is Nothing) Then
                RaiseEvent LABELRowDeleting(Me, New LABELRowChangeEvent(CType(e.Row,LABELRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveLABELRow(ByVal row As LABELRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As DataPall = New DataPall
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "LABELDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class LABELRow
        Inherits Global.System.Data.DataRow
        
        Private tableLABEL As LABELDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableLABEL = CType(Me.Table,LABELDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PPREFX() As String
            Get
                Try 
                    Return CType(Me(Me.tableLABEL.PPREFXColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PPREFX' in table 'LABEL' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLABEL.PPREFXColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PSEQNO() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableLABEL.PSEQNOColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PSEQNO' in table 'LABEL' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLABEL.PSEQNOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PDELNO() As String
            Get
                Try 
                    Return CType(Me(Me.tableLABEL.PDELNOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PDELNO' in table 'LABEL' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLABEL.PDELNOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PCUST() As String
            Get
                Try 
                    Return CType(Me(Me.tableLABEL.PCUSTColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PCUST' in table 'LABEL' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLABEL.PCUSTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PMAKER() As String
            Get
                Try 
                    Return CType(Me(Me.tableLABEL.PMAKERColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PMAKER' in table 'LABEL' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLABEL.PMAKERColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PPART() As String
            Get
                Return CType(Me(Me.tableLABEL.PPARTColumn),String)
            End Get
            Set
                Me(Me.tableLABEL.PPARTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PPDCHG() As String
            Get
                Return CType(Me(Me.tableLABEL.PPDCHGColumn),String)
            End Get
            Set
                Me(Me.tableLABEL.PPDCHGColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PSENO() As String
            Get
                Try 
                    Return CType(Me(Me.tableLABEL.PSENOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PSENO' in table 'LABEL' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLABEL.PSENOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PBQTY() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableLABEL.PBQTYColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PBQTY' in table 'LABEL' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLABEL.PBQTYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PEMTRY() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableLABEL.PEMTRYColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PEMTRY' in table 'LABEL' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLABEL.PEMTRYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PQRDAT() As String
            Get
                Return CType(Me(Me.tableLABEL.PQRDATColumn),String)
            End Get
            Set
                Me(Me.tableLABEL.PQRDATColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PITEM() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableLABEL.PITEMColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PITEM' in table 'LABEL' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLABEL.PITEMColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PDELDT() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableLABEL.PDELDTColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PDELDT' in table 'LABEL' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLABEL.PDELDTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PMODEL() As String
            Get
                Try 
                    Return CType(Me(Me.tableLABEL.PMODELColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PMODEL' in table 'LABEL' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLABEL.PMODELColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PDESC1() As String
            Get
                Try 
                    Return CType(Me(Me.tableLABEL.PDESC1Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PDESC1' in table 'LABEL' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLABEL.PDESC1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PSTAT() As String
            Get
                Return CType(Me(Me.tableLABEL.PSTATColumn),String)
            End Get
            Set
                Me(Me.tableLABEL.PSTATColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PCRDT() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableLABEL.PCRDTColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PCRDT' in table 'LABEL' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLABEL.PCRDTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PCTMT() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableLABEL.PCTMTColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PCTMT' in table 'LABEL' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLABEL.PCTMTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPPREFXNull() As Boolean
            Return Me.IsNull(Me.tableLABEL.PPREFXColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPPREFXNull()
            Me(Me.tableLABEL.PPREFXColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPSEQNONull() As Boolean
            Return Me.IsNull(Me.tableLABEL.PSEQNOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPSEQNONull()
            Me(Me.tableLABEL.PSEQNOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPDELNONull() As Boolean
            Return Me.IsNull(Me.tableLABEL.PDELNOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPDELNONull()
            Me(Me.tableLABEL.PDELNOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPCUSTNull() As Boolean
            Return Me.IsNull(Me.tableLABEL.PCUSTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPCUSTNull()
            Me(Me.tableLABEL.PCUSTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPMAKERNull() As Boolean
            Return Me.IsNull(Me.tableLABEL.PMAKERColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPMAKERNull()
            Me(Me.tableLABEL.PMAKERColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPSENONull() As Boolean
            Return Me.IsNull(Me.tableLABEL.PSENOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPSENONull()
            Me(Me.tableLABEL.PSENOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPBQTYNull() As Boolean
            Return Me.IsNull(Me.tableLABEL.PBQTYColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPBQTYNull()
            Me(Me.tableLABEL.PBQTYColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPEMTRYNull() As Boolean
            Return Me.IsNull(Me.tableLABEL.PEMTRYColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPEMTRYNull()
            Me(Me.tableLABEL.PEMTRYColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPITEMNull() As Boolean
            Return Me.IsNull(Me.tableLABEL.PITEMColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPITEMNull()
            Me(Me.tableLABEL.PITEMColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPDELDTNull() As Boolean
            Return Me.IsNull(Me.tableLABEL.PDELDTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPDELDTNull()
            Me(Me.tableLABEL.PDELDTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPMODELNull() As Boolean
            Return Me.IsNull(Me.tableLABEL.PMODELColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPMODELNull()
            Me(Me.tableLABEL.PMODELColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPDESC1Null() As Boolean
            Return Me.IsNull(Me.tableLABEL.PDESC1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPDESC1Null()
            Me(Me.tableLABEL.PDESC1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPCRDTNull() As Boolean
            Return Me.IsNull(Me.tableLABEL.PCRDTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPCRDTNull()
            Me(Me.tableLABEL.PCRDTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPCTMTNull() As Boolean
            Return Me.IsNull(Me.tableLABEL.PCTMTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPCTMTNull()
            Me(Me.tableLABEL.PCTMTColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class LABELRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As LABELRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As LABELRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As LABELRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
